name: sample-ci

on: [workflow_dispatch]

jobs:
  ubuntu:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: sample install packages
        run: sudo apt update -y && sudo apt install -y openjdk-11-jdk
